### ISSUE TITLE
fuck

### ISSUE THREAD

**Issue by DanKGooGLy** [CraXell/CraXell#1]

**Comment by MoltenCoreDev** [comment]
needs immidiate fix

**Comment by vbajs** [comment]
> needs immidiate fix

__Adds won't fix label__

Sureeeeeeeee....

**Comment by DanKGooGLy** [comment]
OK

**Comment by MoltenCoreDev** [comment]
> > needs immidiate fix
> 
> **Adds won't fix label**
> 
> Sureeeeeeeee....

fixed

**Comment by MoltenCoreDev** [comment]
@vbajs you need to finish this asap!!!!!
